### ISSUE TITLE
A method named 'kadira.profileCpu' is already defined

### ISSUE THREAD

**Issue by Sivli-Embir** [meteorhacks/kadira-profiler#2]
With the following in my packages:

```
meteorhacks:kadira-profiler
meteorhacks:zones
meteorhacks:kadira
```

Meteor fails startup. The Kadira site recommended I add zones and profiler, is that out of date?

**Comment by Sivli-Embir** [comment]
This goes away with:

```
# meteorhacks:kadira-profiler
meteorhacks:zones
meteorhacks:kadira
```

**Comment by arunoda** [comment]
Hi, 

Try this. 

First do: `meteor refresh` then install the `meteorhacks:kadira-profiler`.
If that didn't works, try to remove kadira and add again.

**Comment by Sivli-Embir** [comment]
Just tried, no luck.

I tried:

```
meteorhacks:kadira-profiler
# meteorhacks:zones
# meteorhacks:kadira
```

and I still get the same issue! 

When you say remove Kadira are you talking something more extreme? 

For context:

> $ meteor --version
> Meteor 1.0.3.1

**Comment by arunoda** [comment]
Then try this `meteor add meteorhacks:kadira-profiler@1.0.2`

**Comment by Sivli-Embir** [comment]
Nice, works! I had not used the `meteor add` command in some time. Looks like it was not adding dependancies as well.

**Comment by arunoda** [comment]
Great.

**Comment by Sivli-Embir** [comment]
Just tested on Kadira, works great! Thanks and good job. Keep it up!

**Comment by arunoda** [comment]
Thanks.
