### ISSUE TITLE
Where to add export KADIRA_PROFILE_LOCALLY=1?

### ISSUE THREAD

**Issue by hongbo-miao** [meteorhacks/kadira-profiler#5]
Hi, @arunoda , where should I add export `KADIRA_PROFILE_LOCALLY=1`?

I tried to add in **kadira.js**, but it does not work.
And I cannot find any info online.

Can you make the tutorial more clear? Any support link will also help. Thanks

**Comment by arunoda** [comment]
This is an environment variable. Try to set it on locally or where you deploy. 

Simply Google search will help you.

**Comment by hongbo-miao** [comment]
@arunoda oh, thanks for letting me know!
